# Generated by Django 4.2.21 on 2025-05-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
    ]
